version: "3.7"

volumes:
  front_node_modules:
  back_node_modules:
  dbvolume:

services:
  mongo:
    container_name: mongo
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: souvenirs-dev
    volumes:
      - dbvolume:/data/
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - "27017:27017"

  backend:
    container_name: backend
    restart: always
    build: ./backend
    volumes:
      - ./backend:/usr/src/app/
      -  back_node_modules:/usr/src/app/backend/node_modules/
    command: bash -c "npm install && npm run docker"
    links:
      - mongo
    ports:
      - "8080:8080"

  frontend:
    container_name: frontend
    restart: on-failure
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app/
      -  front_node_modules:/usr/src/app/frontend/node_modules/
    command: bash -c "npm install && npm start"
    links:
      - backend
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true